### ISSUE TITLE
Conflicting error with latest updates

### ISSUE THREAD

**Issue by PatteDeFruit** [bennett-sh/hm-safehouse-colors#1]
Hello there!

It seems that your mod is not working anymore after HITMAN and Simple Mod Framework latest updates:

==

DEBUG	Applying patch C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\Mods\BSh.SafehouseColors\0content\chunk29\gear_wall_large.entity.patch.json
DEBUG	Applying patch C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\Mods\BSh.SafehouseColors\0content\chunk29\gear_wall_medium.entity.patch.json
DEBUG	Applying patch C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\Mods\BSh.SafehouseColors\0content\chunk29\gear_wall_small.entity.patch.json
DEBUG	Applying patch C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\Mods\BSh.SafehouseColors\0content\chunk29\wardrobe.entity.patch.json
DEBUG	Applying patch C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\Mods\BSh.SafehouseColors\0content\chunk29\safehouse.entity.patch.json
Error: Failure converting QN entity to RT

Caused by:
    0: Failure getting pin connections for event
    1: entity_id_to_index_mapping.get(match & trigger_entity
       {
           RefMaybeConstantValue :: Ref(Ref :: Short(Some(id))) => id,
           RefMaybeConstantValue ::
           RefWithConstantValue(RefWithConstantValue
           { entity_ref : Ref :: Short(Some(id)), value : _ }) => id, _ => bail!
           ("Invalid to_id for trigger on events")
       }) at lib.rs:4722
[33mWARN[39m	Error reporting is disabled; if you experience this issue again, please enable it so that the problem can be debugged.
[31mERROR[39m	Unhandled promise rejection! Error: Command failed: "Third-Party\quickentity-rs.exe" entity generate --input "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\QuickEntityJSON.json" --output-factory "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\temp.TEMP.json" --output-factory-meta "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\00A9B93A825F5BDC.TEMP.meta.JSON" --output-blueprint "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\temp.TBLU.json" --output-blueprint-meta "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\005BA5CA6AC00627.TBLU.meta.JSON"
Promise {
  <rejected> Error: Command failed: "Third-Party\quickentity-rs.exe" entity generate --input "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\QuickEntityJSON.json" --output-factory "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\temp.TEMP.json" --output-factory-meta "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\00A9B93A825F5BDC.TEMP.meta.JSON" --output-blueprint "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\temp.TBLU.json" --output-blueprint-meta "C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\Simple Mod Framework\patchWorker4\005BA5CA6AC00627.TBLU.meta.JSON"
      at execCommand (C:\snapshot\simple-mod-framework\compiled\quickentity-rs.js)
      at Object.generate (C:\snapshot\simple-mod-framework\compiled\quickentity-rs.js)
      at C:\snapshot\simple-mod-framework\compiled\patchWorker.js
      at async C:\snapshot\simple-mod-framework\node_modules\piscina\dist\src\worker.js
}

==

Thank you for checking this out!

Regards,
PatteDeFruit

**Comment by bennett-sh** [comment]
Hello Patte,
thanks for reaching out and reporting the issue! I'll be looking into the
issue tomorrow so you can expect a fix by either tomorrow or saturday
(though I can't promise anything).

Regards, BSh

**Comment by PatteDeFruit** [comment]
No problem, take your time!
So what was causing the issue?
All that matters is that you are aware of the compatibility problem.
Thank you for your time, and cya later!

Regards,
PatteDeFruit

**Comment by bennett-sh** [comment]
This now has been fixed. Do note that after this fix there still are a few green lights left but I'll patch them out soon.

**Comment by PatteDeFruit** [comment]
Awesome thanks for the quick fix dude!
